name: Go

on:
  push:

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
      #  os: [ubuntu-latest, windows-latest]
      # macOS doesn't work due to some build-error of jpegdecode
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: --Linux-- Install mingw
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt-get install -y gcc-mingw-w64

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}

    - name: Get dependencies
      run: |
        export GOPATH=$(go env GOPATH)
        echo "GOPATH is $GOPATH"
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
      shell: bash

    - name: Build & Install
      run: make install
      shell: bash

    - name: Lint
      run: make lint
      shell: bash

    - name: Test
      run: make test

    - name: --Linux--- Upload binaries
      if: ${{ runner.os == 'Linux' }}
      uses: actions/upload-artifact@v2
      with:
        name: rac-linux
        path: ${{ env.HOME }}/go/bin/rac

    - name: --macOS--- Upload binaries
      if: ${{ runner.os == 'macOS' }}
      uses: actions/upload-artifact@v2
      with:
        name: rac-mac
        path: ${{ env.HOME }}/go/bin/rac

    - name: --Windows-- Upload binaries
      if: ${{ runner.os == 'Windows' }}
      uses: actions/upload-artifact@v2
      with:
        name: rac-win.exe
        path: ${{ env.HOME }}/go/bin/rac.exe
