name: Releases

on:
  push:
    tags:
    - 'v*'

jobs:

  build:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: --Linux-- Draft release notes only run once and early
      if: ${{ runner.os == 'Linux' }}
      uses: release-drafter/release-drafter@v5
      with:
        config-name: release-notes.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        export GOPATH=$(go env GOPATH)
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
      shell: bash

    - name: Build & Install
      run: make install
      shell: bash

    - name: --Linux--- Bundle binaries
      if: ${{ runner.os == 'Linux' }}
      run: |
        tar -czvf "Rac for Linux.tar.gz" /home/runner/go/bin/rac

    - name: --macOS--- Bundle binaries
      if: ${{ runner.os == 'macOS' }}
      run: |
        tar -zcvf "Rac for macOS.tar.gz" /Users/runner/go/bin/rac

    - name: --Windows-- Bundle binaries
      if: ${{ runner.os == 'Windows' }}
      run: |
        $compress = @{
          Path = "C:\Users\runneradmin\go\bin\rac.exe"
          CompressionLevel = "Fastest"
          DestinationPath = "C:\Rac for Windows.Zip"
        }
        Compress-Archive @compress
      shell: powershell

    - name: --Linux-- Upload bundle to release
      if: ${{ runner.os == 'Linux' }}
      uses: ncipollo/release-action@v1.6.1
      with:
        artifact: "Rac for Linux.tar.gz"
        allowUpdates: true
        omitBody: true
        omitName: true
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: --macOS-- Upload bundle to release
      if: ${{ runner.os == 'macOS' }}
      uses: ncipollo/release-action@v1.6.1
      with:
        artifact: "Rac for macOS.tar.gz"
        allowUpdates: true
        omitBody: true
        omitName: true
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: --Windows-- Upload bundle to release
      if: ${{ runner.os == 'Windows' }}
      uses: ncipollo/release-action@v1.6.1
      with:
        artifact: "C:\\Rac for Windows.tar.gz"
        allowUpdates: true
        omitBody: true
        omitName: true
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
