name: Releases

on: 
  push:
    tags:
    - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "raccli"
        token: ${{ secrets.GITHUB_TOKEN }}